name: "mgrosen-test"

on:
  workflow_dispatch:
  push:
    branches:    
      - dev

jobs:
  Tester1:
    runs-on: ubuntu-latest
    
    # strategy:
    #   fail-fast: false
      # matrix:
      #   language: [ 'go', 'javascript', 'python', 'ruby' ]
      #   other: ['foo', 'bar']

    outputs:
      outputmatrix: ${{ steps.set-matrix.outputs.matrix }}
        
    steps:
    - name: print matrix data
      id: set-matrix
      run: |
        echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"

  Tester2:
    name: Tester2Name
    runs-on: ubuntu-latest
    needs: Tester1

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.Tester1.outputs.outputmatrix) }}
        
    steps:
    - name: print matrix data
      run: |
        echo "project ${{ matrix.project }}, config ${{ matrix.config }}"
