name: "mgrosen-test"

on:
  workflow_dispatch:
  push:
    branches:    
      - dev

jobs:

  
  Tester1:
    runs-on: ubuntu-latest

    outputs:
      outputmatrix: ${{ steps.set-matrix.outputs.matrix }}
        
    steps:
    - name: print matrix data
      id: set-matrix
      run: |
        echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"

  Tester1BuiltMatrix:
    runs-on: ubuntu-latest
    needs: Tester1

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.Tester1.outputs.outputmatrix) }}
        
    steps:
    - name: print matrix data
      run: |
        echo "project ${{ matrix.project }}, config ${{ matrix.config }}"

  Tester2Script:
    runs-on: ubuntu-latest

    outputs:
      outputmatrix: ${{ steps.set-matrix.outputs.outputmatrix }}
    
    steps:
      - uses: actions/github-script@v7
        id: set-matrix
        with:
          script: |
            const generatedMatrix = []
            
            generatedMatrix.push({
              group: 0
              pythonversion: 2.7
            })

            generatedMatrix.push({
              group: 2
              pythonversion: 3.9
            })
            
            core.setOutput('outputmatrix', { 'include': generatedMatrix })

            
  Tester2BuiltMatrix:
    runs-on: ubuntu-latest
    needs: Tester2Script

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.Tester2Script.outputs.outputmatrix) }}
        
    steps:
    - name: print matrix data
      run: |
        echo "group ${{ matrix.group }}, python-version ${{ matrix.pythonversion }}"
